version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: warehouse
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/warehouse:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/warehouse"
      APP_URL: "http://warehouse.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "e0e6c4979da638644e979ee399b78048"
      APP_HOSTNAME: "warehouse.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/warehouse:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: